feat: update flutter_ume_kit_ui
bytedance/flutter_ume pull request #107
Opened 2023-03-03 07:53 UTC by p709723778

更新 flutter_ume_kit_ui 插件
image: ^3.0.5 升级到   image: ^4.0.15
quiver: ^3.0.1 升级到   quiver: ^3.2.1
mockito: ^5.0.12 升级到  mockito: ^5.3.2

- [x] I have read the [UME contribution document](../CONTRIBUTING.md) and understand how to contribute, commit the code according to the rules. 我已阅读过 UME 贡献文档，并了解如何进行贡献，按照规则提交了代码
- [x] I have added the necessary comments in code to ensure that other contributors can understand the reason for the change. 我在修改中已经添加了必要的注释，以确保便于其他贡献者理解修改原因
- [x] The code has been formatted by dartfmt before push. 代码在提交前已经经过 dartfmt 进行了格式化
- [x] Change does not involve the adjustment of test cases. Or all existing and new tests are passing. 改动不涉及测试用例调整，或 example 工程与单元测试已经完全跑通

If you need help, consider [Join ing the ByteDance Flutter Exchange Group](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8).

如有任何问题，可以[加入字节跳动 Flutter 交流群](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8)。

Or contact [author](mailto:sunkai.dev@bytedance.com).

或随时[联系开发者](mailto:sunkai.dev@bytedance.com)。

2023-03-03 10:38 UTC, talisk commented on kits/flutter_ume_kit_ui/lib/components/color_sucker/color_sucker.dart
> +
这里并非必要的修改，回退一下吧

2023-03-03 10:38 UTC, talisk commented on kits/flutter_ume_kit_ui/lib/components/color_sucker/color_sucker.dart
> +import 'package:image/image.dart' as img;
这里并非必要的修改，回退一下吧

2023-03-03 10:40 UTC, talisk commented on kits/flutter_ume_kit_ui/CHANGELOG.md
> +* mockito: ^5.0.12 升级到 mockito: ^5.3.2
增加下对应英文changelog

```suggestion
## 1.1.1

* image: ^3.0.5 升级到 image: ^4.0.15
* quiver: ^3.0.1 升级到 quiver: ^3.2.1
* mockito: ^5.0.12 升级到 mockito: ^5.3.2

* Bump image from 3.0.5 to 4.0.15 
* Bump quiver from 3.0.1 to 3.2.1
* Bump mockito from 5.0.12 to 5.3.2
```

2023-03-03 10:42 UTC, talisk requested changes
Please fix issues

2023-03-03 11:53 UTC, p709723778 commented
> Please fix issues

已解决以上问题

2023-03-06 03:07 UTC, talisk commented on kits/flutter_ume_kit_ui/CHANGELOG.md
> +
段中间的空行移除掉，中文和英文之间有空行。参考我前面的评论

2023-03-06 03:08 UTC, talisk commented on kits/flutter_ume_kit_ui/pubspec.yaml
> +  # for Cyclops
这是什么意思

2023-03-06 03:09 UTC, talisk requested changes
请根据评论修改

2023-03-06 03:34 UTC, p709723778 commented on kits/flutter_ume_kit_ui/pubspec.yaml
> +  # for Cyclops
不好意思,这里的注释报了单词警告,我以为是错误了,所以加了s.  新的提交我这里恢复了

2023-03-06 03:35 UTC, p709723778 commented on kits/flutter_ume_kit_ui/CHANGELOG.md
> +
👌🏻

2023-03-08 08:51 UTC, talisk approved these changes

2023-03-09 02:48 UTC, p709723778 commented
错误原因非插件修改导致, 是来自 https://github.com/ReactiveCircus/android-emulator-runner/issues/324

2023-03-15 08:50 UTC, chenqiang-ola commented
什么时候能处理下这个

2023-03-15 08:51 UTC, chenqiang-ola commented
@talisk

2023-03-15 08:53 UTC, CCXXXI commented
可以直接用 fork 版本，参考 [Git packages | Dart](https://dart.dev/tools/pub/dependencies#git-packages)

2023-03-30 07:25 UTC, merged