support send response data to dingtalk, feishu, business wechat webho…
bytedance/flutter_ume pull request #47
Opened 2022-01-28 05:49 UTC by linversion

…ok and also support send custom text

Describe what problem this pull request solves and how to solve it. If there is an issue associated with it, please attach a link.

添加了发送request body、request header、response到飞书、钉钉、企业微信机器人的功能，也可以发送自己输入的信息，提高前后端联调效率。

## Pull Request Checklist

- [ ] I have read the [UME contribution document](../CONTRIBUTING.md) and understand how to contribute, commit the code according to the rules. 我已阅读过 UME 贡献文档，并了解如何进行贡献，按照规则提交了代码
- [ ] I have added the necessary comments in code to ensure that other contributors can understand the reason for the change. 我在修改中已经添加了必要的注释，以确保便于其他贡献者理解修改原因
- [ ] The code has been formatted by dartfmt before push. 代码在提交前已经经过 dartfmt 进行了格式化
- [ ] Change does not involve the adjustment of test cases. Or all existing and new tests are passing. 改动不涉及测试用例调整，或 example 工程与单元测试已经完全跑通

If you need help, consider [Join ing the ByteDance Flutter Exchange Group](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8).

如有任何问题，可以[加入字节跳动 Flutter 交流群](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8)。

Or contact [author](mailto:sunkai.dev@bytedance.com).

或随时[联系开发者](mailto:sunkai.dev@bytedance.com)。

2022-01-28 07:47 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +  // 是否使用发送到webhook功能
Please write code comments in English.

2022-01-28 07:48 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +  // 自定义请求体构造器
Please write code comments in English.

2022-01-28 07:48 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +  // 发送response到webhook
Please write code comments in English.

2022-01-28 07:48 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +  // 发送自定义信息到webhook
Please write code comments in English.

2022-01-28 07:48 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +  // 构造对应webhook的请求体格式
Please write code comments in English.

2022-01-28 07:48 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +      //钉钉或微信机器人
Please write code comments in English.

2022-01-28 07:48 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/net/dio_manager.dart
> +      //飞书机器人
Please write code comments in English.

2022-01-28 07:50 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/widgets/custom_message_page.dart
> +// 自定义信息输入页面
Please write code comments in English. And this comment should start with `///`. It indicate that it's a documentation comment.

2022-01-28 07:52 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/widgets/pluggable_state.dart
> +// }
Is this code for testing? You should remove it.

2022-01-28 07:53 UTC, talisk commented on kits/flutter_ume_kit_dio/lib/src/widgets/pluggable_state.dart
> +// }
And you'd best write example code in the `Example` project of `flutter_ume`

2022-01-28 07:57 UTC, talisk requested changes
Please write example code in Example project. And then I will ask @AlexV525 to review the code.

2022-01-28 12:28 UTC, AlexV525 commented
I'm not sure why an interceptor should send such content, but a log interceptor might do so. If you want to collect requests and responses, it might be better to expose the method to obtain, rather than nested the upload function.

FYI @talisk.

2022-01-29 09:51 UTC, linversion commented
> Please write example code in Example project. And then I will ask @AlexV525 to review the code.

When you register the DioInspector, there are three parameter in it's constructor, only the dio is required. Not sure how to write the example code.

2022-09-19 09:37 UTC, closed without merging