[fix] toolbar initial position is incorrect
bytedance/flutter_ume pull request #66
Opened 2022-09-07 10:08 UTC by suli1

Toolbar初始显示位置偏下，有时会被系统导航栏遮挡，显示不全

## Pull Request Checklist

- [ ] I have read the [UME contribution document](../CONTRIBUTING.md) and understand how to contribute, commit the code according to the rules. 我已阅读过 UME 贡献文档，并了解如何进行贡献，按照规则提交了代码
- [ ] I have added the necessary comments in code to ensure that other contributors can understand the reason for the change. 我在修改中已经添加了必要的注释，以确保便于其他贡献者理解修改原因
- [ ] The code has been formatted by dartfmt before push. 代码在提交前已经经过 dartfmt 进行了格式化
- [ ] Change does not involve the adjustment of test cases. Or all existing and new tests are passing. 改动不涉及测试用例调整，或 example 工程与单元测试已经完全跑通

If you need help, consider [Join ing the ByteDance Flutter Exchange Group](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8).

如有任何问题，可以[加入字节跳动 Flutter 交流群](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=67au2f75-3783-41b0-8868-0fc0178f1fd8)。

Or contact [author](mailto:sunkai.dev@bytedance.com).

或随时[联系开发者](mailto:sunkai.dev@bytedance.com)。

2022-09-19 09:36 UTC, talisk requested changes

2022-09-19 09:36 UTC, talisk commented on example/android/app/src/main/AndroidManifest.xml
> -        android:name="io.flutter.app.FlutterApplication"
It seems to have nothing to do with the function modification, should you delete it?

2022-09-19 09:36 UTC, talisk commented on example/android/build.gradle
> -    ext.kotlin_version = '1.3.50'
He seems to have nothing to do with the function modification, should you delete it

2022-09-22 05:56 UTC, suli1 commented
Resolved

2022-09-22 10:27 UTC, talisk commented on lib/core/ui/toolbar_widget.dart
> -    if (_windowSize.isEmpty) {
In some case, `windowsSize` will be empty... I will test it and make sure it couldn't be empty. Please wait a while.

2022-09-26 03:20 UTC, merged